### ISSUE TITLE
Doesn't work with SvelteKit: `document is not defined`

### ISSUE THREAD

**Issue by Mobilpadde** [wobsoriano/svelte-monetization#15]
`"svelte-monetization": "^1.0.0"` doesn't seem to work with `"@sveltejs/kit": "next"`. Sadly.

**Comment by wobsoriano** [comment]
Do you get any errors?

**Comment by Mobilpadde** [comment]
Yes, the `document is not defined`one, as the tittle suggests 😊

**Comment by wobsoriano** [comment]
Try importing the component dynamically onMount

https://stackoverflow.com/questions/69874742/sveltekit-console-error-window-is-not-defined-when-i-import-library

**Comment by Mobilpadde** [comment]
Thanks, that got me thinking the `await` and `svelte:component`'s.

For future people whom might run into this issue:

```svelte
{#await import('svelte-monetization') then c}
  <svelte:component this={c.default} let:isMonetized>
    {#if !isMonetized}
      <div>Ads</div>
    {/if}
  </svelte:component>
{/await}
```

Maybe include this in the README? :dancers:
